### ISSUE TITLE
Seems to ignore tree.paused

### ISSUE THREAD

**Issue by OnyxIdol** [kagenash1/godot-behavior-tree#35]
Hi, I have been using your plugin with great success so far, so thanks for your work! 

However I have now implemented a pause menu of sorts and the behavior tree seems to be still executing - basically even though everything else is frozen, my agents keep moving forward but do nothing else. 

I don't know if you're still working on this but if you do this might be something to look into.

Edit: I did modify the script a little and that seems to do it. Basically only tick the child if the tree is unpaused.

```
func run():

	var blackboard: Blackboard = get_node(_blackboard)
	var bt_root: BTNode = get_child(0)
	var agent: Node = get_node(_agent)
	var tick_result
	
	while is_active:
		if !get_tree().paused:		
			tick_result = bt_root.tick(agent, blackboard)
		
			if tick_result is GDScriptFunctionState:
				tick_result = yield(tick_result, "completed")
		
		if sync_mode == "idle":
			yield(get_tree(), "idle_frame") 
		else:
			yield(get_tree(), "physics_frame")
```

**Comment by kagenash1** [comment]
I think you are using an old version. It's probably my fault, I forgot to update the asset store page.

**Comment by OnyxIdol** [comment]
Yeah I was wondering because Asset Store still shows version 1.1.1 (also still your real name ;)

**Comment by OnyxIdol** [comment]
Hmm doesn't seem to be compatible.

**Comment by kagenash1** [comment]
It's not 100% backwards compatible, I think some things need to change. Do you wanna text me on Discord so I can help you closely? 
I'm kagenashi#8224

**Comment by OnyxIdol** [comment]
Sent a fr
